don't fail migration if system is not encrypted

diff --git a/usr/lib/tik/modules/post/20-mig b/usr/lib/tik/modules/post/20-mig
--- a/usr/lib/tik/modules/post/20-mig
+++ b/usr/lib/tik/modules/post/20-mig
@@ -19,16 +19,11 @@ EOF
 
 if [ "${migrate}" == 1 ]; then
     probe_partitions ${TIK_INSTALL_DEVICE} "crypto_LUKS"
-    if [ -z "${probedpart}" ]; then
-        error "encrypted partition not found"
-    fi
-    prun /usr/sbin/cryptsetup luksOpen --key-file=${tik_keyfile} ${cryptpart} aeon_root
+    [ -z "${probedpart}" ] || prun /usr/sbin/cryptsetup luksOpen --key-file=${tik_keyfile} ${cryptpart} aeon_root
 
     probe_partitions $TIK_INSTALL_DEVICE "btrfs" "/usr/lib/os-release"
 
-    if [ -z "${probedpart}" ]; then
-        error "MIGRATION FAILED: New Installation NOT FOUND"
-    fi
+    [ -n "${probedpart}" ] || error "MIGRATION FAILED: New Installation NOT FOUND"
 
     prun /usr/bin/mkdir ${mig_dir}/mnt
     prun /usr/bin/mount -o compress=zstd:1 ${probedpart} ${mig_dir}/mnt
@@ -71,5 +66,5 @@ if [ "${migrate}" == 1 ]; then
     done
     prun /usr/bin/umount ${mig_dir}/mnt
     prun /usr/bin/rmdir ${mig_dir}/mnt
-    prun /usr/sbin/cryptsetup luksClose aeon_root
+    [ ! -e /dev/mapper/aeon_root ] || prun /usr/sbin/cryptsetup luksClose aeon_root
 fi
