tik-gui: First commit, core functionality working

diff --git a/usr/lib/tik/lib/tik-functions b/usr/lib/tik/lib/tik-functions
--- a/usr/lib/tik/lib/tik-functions
+++ b/usr/lib/tik/lib/tik-functions
@@ -1,72 +1,39 @@
 # SPDX-License-Identifier: MIT
-# SPDX-FileCopyrightText: Copyright 2023 SUSE LLC
+# SPDX-FileCopyrightText: Copyright 2023-2024 SUSE LLC
+# SPDX-FileCopyrightText: Copyright 2023-2024 Richard Brown
 
-
-# Read os-release, to enable those variables to be used elsewhere
-if [ -e /etc/os-release ]; then
-	. /etc/os-release
-else
-	. /usr/lib/os-release
-fi
+log(){
+	echo "[tik][$(date +"%Y%m%d-%T")][LOG]: $*" 1>&2
+}
 
 d(){
 	while true
 	do
 		retval=0
-		# Bash makes it a bit annoying to read the output of a different FD into a variable, it
-		# only supports reading stdout by itself. So redirect 3 to stdout and 1 to the real stdout.
-		exec {stdoutfd}>&1
-		result="$(dialog --backtitle "$TIK_TITLE" --output-fd 3 "$@" 3>&1 1>&${stdoutfd})" || retval=$?
-		# Word splitting makes it necessary to use eval here.
-		eval "exec ${stdoutfd}>&-"
+		result="$(zenity "$@")" || retval=$?
+
 		case $retval in
 		  0)
+			echo "[tik][$(date +"%Y%m%d-%T")][zenity]: zenity $@ exited CODE: $retval" 1>&2
 			return 0
 			;;
 		  1|255)
-			dialog --backtitle "$TIK_TITLE" --yesno $"Do you really want to quit?" 6 80 && exit 1
-			continue
+		    echo "[tik][$(date +"%Y%m%d-%T")][zenity]: zenity $@ exited CODE: $retval" 1>&2
+		    zenity --question --text="Do you really want to quit?" && exit 1
 			;;
 		esac
 	done
 }
 
-udev_pending() {
-    declare DEVICE_TIMEOUT=${DEVICE_TIMEOUT}
-    local limit=30
-    if [[ "${DEVICE_TIMEOUT}" =~ ^[0-9]+$ ]]; then
-        limit=$(((DEVICE_TIMEOUT + 1)/ 2))
-    fi
-    udevadm settle --timeout=${limit}
-}
-
-bool() {
-    # """
-    # provides boolean string true|false for given value.
-    # Only if value matches true return true, in any other
-    # case return false
-    # """
-    local value=$1
-    if [ -n "${value}" ] && [ "${value}" = "true" ] ;then
-        echo "true"
-    else
-        echo "false"
-    fi
-}
-
 warn() {
-    echo "tik Warning: $*" >&2
+    echo "[tik][$(date +"%Y%m%d-%T")][WARN]: $*" 1>&2
+    d --warning --text="$*"
 }
 
-report_and_quit() {
-    local text_message="$1"
-    d --timeout 60 --msgbox "${text_message}" 6 80
-    if [ -n "$dry" ]; then
-        echo "${text_message}"
-        exit 1
-    else
-        reboot -f
-    fi
+error() {
+    echo "[tik][$(date +"%Y%m%d-%T")][ERROR]: $*" 1>&2
+    d --timeout 60 --error --text "$*"
+    exit 1
 }
 
 get_persistent_device_from_unix_node() {
@@ -75,7 +42,6 @@ get_persistent_device_from_unix_node() {
     local node
     local persistent_name
     node=$(basename "${unix_device}")
-    udev_pending
     for persistent_name in /dev/disk/"${schema}"/*; do
         if [ "$(basename "$(readlink "${persistent_name}")")" = "${node}" ];then
             if [[ ${persistent_name} =~ ^/dev/disk/"${schema}"/nvme-eui ]]; then
@@ -86,8 +52,7 @@ get_persistent_device_from_unix_node() {
             return
         fi
     done
-    warn "Could not find ${schema} representation of ${node}"
-    warn "Using original device ${unix_device}"
+    warn "Could not find ${schema} representation of ${node}\n\nUsing original device ${unix_device}"
     echo "${unix_device}"
 }
 
@@ -146,11 +111,11 @@ get_disk() {
         local device_size
         if [ ! -e "${device}" ];then
             local no_dev="Given device ${device} does not exist"
-            report_and_quit "${no_dev}"
+            error "${no_dev}"
         fi
         if [ ! -b "${device}" ];then
             local no_block_dev="Given device ${device} is not a block special"
-            report_and_quit "${no_block_dev}"
+            error "${no_block_dev}"
         fi
         device_meta=$(
             eval lsblk "${blk_opts}" "${device}" |\
@@ -163,7 +128,7 @@ get_disk() {
     fi
     if [ -z "${list_items}" ];then
         local no_device_text="No device(s) for installation found"
-        report_and_quit "${no_device_text}"
+        error "${no_device_text}"
     fi
     disk_list=${list_items}
     if [ -n "${disk_list}" ];then
@@ -181,7 +146,7 @@ get_disk() {
             TIK_INSTALL_DEVICE="${device_array[0]}"
         else
             # manually select from storage list
-            d --menu "Select Installation Disk:" 0 0 0 ${list_items}
+            d --list --column=Disk --column=Size --title="Select Installation Disk:" ${list_items}
             TIK_INSTALL_DEVICE="$result"
         fi
     fi
@@ -211,11 +176,11 @@ get_img() {
         local img_size
         if [ ! -e "${img}" ];then
             local no_img="Given image ${img} does not exist"
-            report_and_quit "${no_img}"
+            error "${no_img}"
         fi
         if [ ! -s "${img}" ];then
             local empty_img="Given image ${img} is empty"
-            report_and_quit "${empty_img}"
+            error "${empty_img}"
         fi
         img_meta=$(
             eval cd $TIK_IMG_DIR && (stat --printf="%n\t%s\n" $img | tr '	' ":")
@@ -228,7 +193,7 @@ get_img() {
     fi
     if [ -z "${list_items}" ];then
         local no_image_text="No images(s) for installation found"
-        report_and_quit "${no_image_text}"
+        error "${no_image_text}"
     fi
     img_list=${list_items}
     if [ -n "${img_list}" ];then
@@ -246,7 +211,7 @@ get_img() {
             TIK_INSTALL_IMAGE="${img_array[0]}"
         else
             # manually select from storage list
-            d --menu "Select Installation Image:" 0 0 0 ${list_items}
+            d --list --column=Disk --column=Size --title="Select Installation Image:" ${list_items}
             TIK_INSTALL_IMAGE="$result"
         fi
     fi
@@ -258,19 +223,13 @@ function dump_image {
     local image_source
     local image_basename
     image_basename=$(basename "${image_source_files}")
-    local load_text="Loading ${image_basename}..."
-    local title_text="Installation..."
 
     local ack_dump_text="Destroying ALL data on\n    ${image_target}\nContinue?"
-    d --yesno "${ack_dump_text}" 8 80
+    d --question --text="${ack_dump_text}"
 
-    if [ -n "$dry" ]; then
-       echo "DEBUG: ${load_text} [${image_target}]..."
-    fi
-    (xzcat ${TIK_IMG_DIR}/${image_source_files} | run dd of=${image_target} bs=64k status=progress) 2>&1 | d --progressbox "${title_text}" 5 80
-    d --infobox "Please Wait..." 5 80
-    sync
-    d --msgbox "${image_basename}\n    has been installed to\n${image_target}" 8 80
+    (xzcat ${TIK_IMG_DIR}/${image_source_files} | prun dd of=${image_target} bs=64k) | d --progress --title="Installing.." --pulsate --auto-close --no-cancel
+    prun sync | d --progress --title="Please Wait..." --pulsate --auto-close --no-cancel
+    d --info --text="${image_basename}\n    has been installed to\n${image_target}"
 }
 
 
